// 常用国家列表：label 为中文显示，value 为英文标准名（存入数据库，对接 ECharts 世界地图）。
// cn 与 label 相同，保留字段用于英文→中文反查（见 countryLabel）。
const RAW = [
  ['中国', 'China'],
  ['美国', 'United States'],
  ['英国', 'United Kingdom'],
  ['德国', 'Germany'],
  ['法国', 'France'],
  ['意大利', 'Italy'],
  ['西班牙', 'Spain'],
  ['荷兰', 'Netherlands'],
  ['比利时', 'Belgium'],
  ['瑞士', 'Switzerland'],
  ['瑞典', 'Sweden'],
  ['挪威', 'Norway'],
  ['丹麦', 'Denmark'],
  ['芬兰', 'Finland'],
  ['奥地利', 'Austria'],
  ['波兰', 'Poland'],
  ['捷克', 'Czech Republic'],
  ['匈牙利', 'Hungary'],
  ['罗马尼亚', 'Romania'],
  ['希腊', 'Greece'],
  ['葡萄牙', 'Portugal'],
  ['俄罗斯', 'Russia'],
  ['乌克兰', 'Ukraine'],
  ['土耳其', 'Turkey'],
  ['以色列', 'Israel'],
  ['沙特阿拉伯', 'Saudi Arabia'],
  ['阿联酋', 'United Arab Emirates'],
  ['卡塔尔', 'Qatar'],
  ['科威特', 'Kuwait'],
  ['阿曼', 'Oman'],
  ['巴林', 'Bahrain'],
  ['约旦', 'Jordan'],
  ['黎巴嫩', 'Lebanon'],
  ['叙利亚', 'Syria'],
  ['也门', 'Yemen'],
  ['伊朗', 'Iran'],
  ['伊拉克', 'Iraq'],
  ['巴基斯坦', 'Pakistan'],
  ['印度', 'India'],
  ['孟加拉国', 'Bangladesh'],
  ['斯里兰卡', 'Sri Lanka'],
  ['泰国', 'Thailand'],
  ['越南', 'Vietnam'],
  ['马来西亚', 'Malaysia'],
  ['印度尼西亚', 'Indonesia'],
  ['菲律宾', 'Philippines'],
  ['新加坡', 'Singapore'],
  ['缅甸', 'Myanmar'],
  ['柬埔寨', 'Cambodia'],
  ['日本', 'Japan'],
  ['韩国', 'South Korea'],
  ['澳大利亚', 'Australia'],
  ['新西兰', 'New Zealand'],
  ['加拿大', 'Canada'],
  ['墨西哥', 'Mexico'],
  ['巴西', 'Brazil'],
  ['阿根廷', 'Argentina'],
  ['智利', 'Chile'],
  ['哥伦比亚', 'Colombia'],
  ['秘鲁', 'Peru'],
  ['厄瓜多尔', 'Ecuador'],
  ['委内瑞拉', 'Venezuela'],
  ['玻利维亚', 'Bolivia'],
  ['乌拉圭', 'Uruguay'],
  ['巴拉圭', 'Paraguay'],
  ['巴拿马', 'Panama'],
  ['危地马拉', 'Guatemala'],
  ['洪都拉斯', 'Honduras'],
  ['哥斯达黎加', 'Costa Rica'],
  ['多米尼加', 'Dominican Republic'],
  ['古巴', 'Cuba'],
  ['南非', 'South Africa'],
  ['尼日利亚', 'Nigeria'],
  ['埃及', 'Egypt'],
  ['肯尼亚', 'Kenya'],
  ['埃塞俄比亚', 'Ethiopia'],
  ['加纳', 'Ghana'],
  ['坦桑尼亚', 'Tanzania'],
  ['摩洛哥', 'Morocco'],
  ['阿尔及利亚', 'Algeria'],
  ['利比亚', 'Libya'],
  ['突尼斯', 'Tunisia'],
  ['苏丹', 'Sudan'],
  ['安哥拉', 'Angola'],
  ['莫桑比克', 'Mozambique'],
  ['刚果（金）', 'DR Congo'],
  ['赞比亚', 'Zambia'],
  ['乌干达', 'Uganda'],
  ['喀麦隆', 'Cameroon'],
  ['科特迪瓦', "Côte d'Ivoire"],
  ['塞内加尔', 'Senegal'],
  ['马达加斯加', 'Madagascar'],
  ['津巴布韦', 'Zimbabwe'],
  ['纳米比亚', 'Namibia'],
  ['哈萨克斯坦', 'Kazakhstan'],
  ['乌兹别克斯坦', 'Uzbekistan'],
  ['土库曼斯坦', 'Turkmenistan'],
  ['塔吉克斯坦', 'Tajikistan'],
  ['吉尔吉斯斯坦', 'Kyrgyzstan'],
  ['阿富汗', 'Afghanistan'],
  ['阿塞拜疆', 'Azerbaijan'],
  ['格鲁吉亚', 'Georgia'],
  ['亚美尼亚', 'Armenia'],
  ['蒙古', 'Mongolia'],
]

// label=中文显示，value=英文（存库值），en 保留用于搜索
export const COUNTRIES = RAW.map(([cn, en]) => ({ label: cn, value: en, en }))

// 英文标准名 → 中文，用于把库里存的英文显示成中文
const EN_TO_CN = Object.fromEntries(RAW.map(([cn, en]) => [en, cn]))

// 显示函数：英文存值 → 中文；遇到历史中文/脏数据则原样返回
export function countryLabel(value) {
  if (!value) return '-'
  return EN_TO_CN[value] || value
}

export function filterCountries(input) {
  if (!input) return COUNTRIES
  const kw = input.toLowerCase()
  return COUNTRIES.filter(
    c => c.label.includes(input) || c.en.toLowerCase().includes(kw)
  )
}
