// 常用国家列表：label 为中文显示，en 为英文（用于搜索），value 存储中文名
export const COUNTRIES = [
  { label: '中国', en: 'China', value: '中国' },
  { label: '美国', en: 'United States', value: '美国' },
  { label: '英国', en: 'United Kingdom', value: '英国' },
  { label: '德国', en: 'Germany', value: '德国' },
  { label: '法国', en: 'France', value: '法国' },
  { label: '意大利', en: 'Italy', value: '意大利' },
  { label: '西班牙', en: 'Spain', value: '西班牙' },
  { label: '荷兰', en: 'Netherlands', value: '荷兰' },
  { label: '比利时', en: 'Belgium', value: '比利时' },
  { label: '瑞士', en: 'Switzerland', value: '瑞士' },
  { label: '瑞典', en: 'Sweden', value: '瑞典' },
  { label: '挪威', en: 'Norway', value: '挪威' },
  { label: '丹麦', en: 'Denmark', value: '丹麦' },
  { label: '芬兰', en: 'Finland', value: '芬兰' },
  { label: '奥地利', en: 'Austria', value: '奥地利' },
  { label: '波兰', en: 'Poland', value: '波兰' },
  { label: '捷克', en: 'Czech Republic', value: '捷克' },
  { label: '匈牙利', en: 'Hungary', value: '匈牙利' },
  { label: '罗马尼亚', en: 'Romania', value: '罗马尼亚' },
  { label: '希腊', en: 'Greece', value: '希腊' },
  { label: '葡萄牙', en: 'Portugal', value: '葡萄牙' },
  { label: '俄罗斯', en: 'Russia', value: '俄罗斯' },
  { label: '乌克兰', en: 'Ukraine', value: '乌克兰' },
  { label: '土耳其', en: 'Turkey', value: '土耳其' },
  { label: '以色列', en: 'Israel', value: '以色列' },
  { label: '沙特阿拉伯', en: 'Saudi Arabia', value: '沙特阿拉伯' },
  { label: '阿联酋', en: 'United Arab Emirates', value: '阿联酋' },
  { label: '卡塔尔', en: 'Qatar', value: '卡塔尔' },
  { label: '科威特', en: 'Kuwait', value: '科威特' },
  { label: '阿曼', en: 'Oman', value: '阿曼' },
  { label: '巴林', en: 'Bahrain', value: '巴林' },
  { label: '约旦', en: 'Jordan', value: '约旦' },
  { label: '黎巴嫩', en: 'Lebanon', value: '黎巴嫩' },
  { label: '叙利亚', en: 'Syria', value: '叙利亚' },
  { label: '也门', en: 'Yemen', value: '也门' },
  { label: '伊朗', en: 'Iran', value: '伊朗' },
  { label: '伊拉克', en: 'Iraq', value: '伊拉克' },
  { label: '巴基斯坦', en: 'Pakistan', value: '巴基斯坦' },
  { label: '印度', en: 'India', value: '印度' },
  { label: '孟加拉国', en: 'Bangladesh', value: '孟加拉国' },
  { label: '斯里兰卡', en: 'Sri Lanka', value: '斯里兰卡' },
  { label: '泰国', en: 'Thailand', value: '泰国' },
  { label: '越南', en: 'Vietnam', value: '越南' },
  { label: '马来西亚', en: 'Malaysia', value: '马来西亚' },
  { label: '印度尼西亚', en: 'Indonesia', value: '印度尼西亚' },
  { label: '菲律宾', en: 'Philippines', value: '菲律宾' },
  { label: '新加坡', en: 'Singapore', value: '新加坡' },
  { label: '缅甸', en: 'Myanmar', value: '缅甸' },
  { label: '柬埔寨', en: 'Cambodia', value: '柬埔寨' },
  { label: '日本', en: 'Japan', value: '日本' },
  { label: '韩国', en: 'South Korea', value: '韩国' },
  { label: '澳大利亚', en: 'Australia', value: '澳大利亚' },
  { label: '新西兰', en: 'New Zealand', value: '新西兰' },
  { label: '加拿大', en: 'Canada', value: '加拿大' },
  { label: '墨西哥', en: 'Mexico', value: '墨西哥' },
  { label: '巴西', en: 'Brazil', value: '巴西' },
  { label: '阿根廷', en: 'Argentina', value: '阿根廷' },
  { label: '智利', en: 'Chile', value: '智利' },
  { label: '哥伦比亚', en: 'Colombia', value: '哥伦比亚' },
  { label: '秘鲁', en: 'Peru', value: '秘鲁' },
  { label: '厄瓜多尔', en: 'Ecuador', value: '厄瓜多尔' },
  { label: '委内瑞拉', en: 'Venezuela', value: '委内瑞拉' },
  { label: '玻利维亚', en: 'Bolivia', value: '玻利维亚' },
  { label: '乌拉圭', en: 'Uruguay', value: '乌拉圭' },
  { label: '巴拉圭', en: 'Paraguay', value: '巴拉圭' },
  { label: '巴拿马', en: 'Panama', value: '巴拿马' },
  { label: '危地马拉', en: 'Guatemala', value: '危地马拉' },
  { label: '洪都拉斯', en: 'Honduras', value: '洪都拉斯' },
  { label: '哥斯达黎加', en: 'Costa Rica', value: '哥斯达黎加' },
  { label: '多米尼加', en: 'Dominican Republic', value: '多米尼加' },
  { label: '古巴', en: 'Cuba', value: '古巴' },
  { label: '南非', en: 'South Africa', value: '南非' },
  { label: '尼日利亚', en: 'Nigeria', value: '尼日利亚' },
  { label: '埃及', en: 'Egypt', value: '埃及' },
  { label: '肯尼亚', en: 'Kenya', value: '肯尼亚' },
  { label: '埃塞俄比亚', en: 'Ethiopia', value: '埃塞俄比亚' },
  { label: '加纳', en: 'Ghana', value: '加纳' },
  { label: '坦桑尼亚', en: 'Tanzania', value: '坦桑尼亚' },
  { label: '摩洛哥', en: 'Morocco', value: '摩洛哥' },
  { label: '阿尔及利亚', en: 'Algeria', value: '阿尔及利亚' },
  { label: '利比亚', en: 'Libya', value: '利比亚' },
  { label: '突尼斯', en: 'Tunisia', value: '突尼斯' },
  { label: '苏丹', en: 'Sudan', value: '苏丹' },
  { label: '安哥拉', en: 'Angola', value: '安哥拉' },
  { label: '莫桑比克', en: 'Mozambique', value: '莫桑比克' },
  { label: '刚果（金）', en: 'DR Congo', value: '刚果（金）' },
  { label: '赞比亚', en: 'Zambia', value: '赞比亚' },
  { label: '乌干达', en: 'Uganda', value: '乌干达' },
  { label: '喀麦隆', en: 'Cameroon', value: '喀麦隆' },
  { label: '科特迪瓦', en: "Côte d'Ivoire", value: '科特迪瓦' },
  { label: '塞内加尔', en: 'Senegal', value: '塞内加尔' },
  { label: '马达加斯加', en: 'Madagascar', value: '马达加斯加' },
  { label: '津巴布韦', en: 'Zimbabwe', value: '津巴布韦' },
  { label: '纳米比亚', en: 'Namibia', value: '纳米比亚' },
  { label: '哈萨克斯坦', en: 'Kazakhstan', value: '哈萨克斯坦' },
  { label: '乌兹别克斯坦', en: 'Uzbekistan', value: '乌兹别克斯坦' },
  { label: '土库曼斯坦', en: 'Turkmenistan', value: '土库曼斯坦' },
  { label: '塔吉克斯坦', en: 'Tajikistan', value: '塔吉克斯坦' },
  { label: '吉尔吉斯斯坦', en: 'Kyrgyzstan', value: '吉尔吉斯斯坦' },
  { label: '阿富汗', en: 'Afghanistan', value: '阿富汗' },
  { label: '阿塞拜疆', en: 'Azerbaijan', value: '阿塞拜疆' },
  { label: '格鲁吉亚', en: 'Georgia', value: '格鲁吉亚' },
  { label: '亚美尼亚', en: 'Armenia', value: '亚美尼亚' },
  { label: '蒙古', en: 'Mongolia', value: '蒙古' },
]

export function filterCountries(input) {
  if (!input) return COUNTRIES
  const kw = input.toLowerCase()
  return COUNTRIES.filter(
    c => c.label.includes(input) || c.en.toLowerCase().includes(kw)
  )
}
